src/LeagueDraft.Web/ViewModels/AllPositionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LeagueDraft.Web.ViewModels
{
    public class AllPositionsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImageUrl { get; set; }
    }
}

src/LeagueDraft.Web/ViewModels/DraftViewModel.cs
using LeagueDraft.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LeagueDraft.Web.ViewModels
{
    public class DraftViewModel
    {
        public Champion Champion { get; set; }

        public IEnumerable<Item> Build { get; set; }

        public Position Position { get; set; }

        public IEnumerable<SummonerSpell> SummonerSpells { get; set; }
    }
}

src/LeagueDraft.Web/Controllers/DraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeagueDraft.Common.Constants;
using LeagueDraft.Services.Interfaces;
using LeagueDraft.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LeagueDraft.Web.Controllers
{
    public class DraftController : Controller
    {
        private readonly IChampionService championService;
        private readonly IItemService itemService;
        private readonly IPositionService positionService;
        private readonly ISummonerSpellService summonerSpellService;

        public DraftController(IChampionService championService,
            IItemService itemService,
            IPositionService positionService,
            ISummonerSpellService summonerSpellService)
        {
            this.championService = championService;
            this.itemService = itemService;
            this.positionService = positionService;
            this.summonerSpellService = summonerSpellService;
        }


        [Route("/soloDraft")]
        public async Task<IActionResult> MakeSoloDraft()
        {
            var champion = await this.championService.GetRandomChampionAsync();

            var build = await this.itemService.GetRandomBuildAsync();

            var position = await this.positionService.GetRandomPositionAsync();

            var summonerSpells = await this.summonerSpellService.GetRandomSummonerSpellsAsync();

            if (PositionConstants.Jungle.Equals(position.Name))
            {
                build = await this.itemService.GetRandomJungleBuildAsync();
                summonerSpells = await this.summonerSpellService.GetJunglerSummonerSpellsAsync();
            }
            else if (PositionConstants.Support.Equals(position.Name))
            {
                build = await this.itemService.GetRandomSupportBuildAsync();
            }

            var draftViewModel = new DraftViewModel()
            {
                Champion = champion,
                Build = build,
                Position = position,
                SummonerSpells = summonerSpells
            };

            return this.View(draftViewModel);
        }

        [Route("/champion/{id}")]
        public async Task<IActionResult> MakeDraftByChampion(int id)
        {
            var champion = await this.championService.GetChampionByIdAsync(id);

            if (champion == null)
            {
                return StatusCode(404);
            };

            var build = await this.itemService.GetRandomBuildAsync();

            var position = await this.positionService.GetRandomPositionAsync();

            var summonerSpells = await this.summonerSpellService.GetRandomSummonerSpellsAsync();

            if (PositionConstants.Jungle.Equals(position.Name))
            {
                build = await this.itemService.GetRandomJungleBuildAsync();
                summonerSpells = await this.summonerSpellService.GetJunglerSummonerSpellsAsync();
            }
            else if (PositionConstants.Support.Equals(position.Name))
            {
                build = await this.itemService.GetRandomSupportBuildAsync();
            }

            var draftViewModel = new DraftViewModel()
            {
                Champion = champion,
                Build = build,
                Position = position,
                SummonerSpells = summonerSpells
            };

            return this.View(draftViewModel);
        }

        [Route("/positions")]
        public async Task<IActionResult> AllPositions()
        {
            var allPositions = await this.positionService.GetAllPositionsAsync();

            var listedViewModel = new List<AllPositionsViewModel>();

            foreach (var position in allPositions)
            {
                var viewModel = new AllPositionsViewModel();

                viewModel.Id = position.Id;
                viewModel.Name = position.Name;
                viewModel.ImageUrl = position.ImageUrl;

                listedViewModel.Add(viewModel);
            }

            return View(listedViewModel);
        }

        [Route("/position/{id}")]
        public async Task<IActionResult> MakeDraftByPosition(int id)
        {
            var position = await this.positionService.GetPositionByIdAsync(id);

            if (position == null)
            {
                return StatusCode(404);
            };

            var champion = await this.championService.GetRandomChampionAsync();

            if (champion == null)
            {
                return NotFound();
            }

            var build = await this.itemService.GetRandomBuildForPositionAsync(id);

            var summonerSpells = await this.summonerSpellService.GetRandomSummonerSpellsAsync();

            if (PositionConstants.Jungle.Equals(position.Name))
            {
                summonerSpells = await this.summonerSpellService.GetJunglerSummonerSpellsAsync();
            }

            var draftByPositionViewModel = new DraftByPositionViewModel()
            {
                Champion = champion,
                Build = build,
                Position = position,
                SummonerSpells = summonerSpells

            };

            return this.View(draftByPositionViewModel);
        }

        [Route("/teamDraft")]
        public async Task<IActionResult> MakeTeamDraft()
        {
            var teamDraft = new List<RandomDraftViewModel>();

            for (int i = 0; i < 5; i++)
            {
                var champion = await this.championService.GetRandomChampionAsync();

                var build = await this.itemService.GetRandomBuildAsync();

                var summonerSpells = await this.summonerSpellService.GetRandomSummonerSpellsAsync();

                if (i == 1)
                {
                    build = await this.itemService.GetRandomJungleBuildAsync();

                    summonerSpells = await this.summonerSpellService.GetJunglerSummonerSpellsAsync();
                }
                else if (i == 4)
                {
                    build = await this.itemService.GetRandomSupportBuildAsync();
                }

                var draft = new RandomDraftViewModel()
                {
                    Champion = champion,
                    Build = build,
                    SummonerSpells = summonerSpells

                };
                teamDraft.Add(draft);
            }

            var teamDraftViewModel = new TeamDraftViewModel()
            {
                TeamSet = teamDraft
            };

            return this.View(teamDraftViewModel);
        }
    }
}

src/LeagueDraft.Web/Views/Draft/AllPositions.cshtml
@model IEnumerable<AllPositionsViewModel>
@{
    ViewData["Title"] = "Positions";
}
<div class="text-center">
    <h1 class="display-4">Lane picking...</h1>
</div>
<br />
<div class="container text-center">
    <div>
        @foreach (var position in Model)
        {
            <div class="col-sm">
                <br />
                <a asp-action="MakeDraftByPosition" asp-controller="Draft" asp-route-id="@position.Id"><img src="@position.ImageUrl" alt="Alternate Text" width="50" /></a>
            </div>
        }
    </div>
</div>

src/LeagueDraft.Web/Views/Draft/MakeDraftByChampion.cshtml
@model DraftViewModel
@{
    ViewData["Title"] = Model.Champion.Name + " " + "Draft";
}

<div class="text-center">
    <h1 class="display-4">@Model.Champion.Name Setup</h1>
</div>
<br />
<div class="card text-center">
    <div class="card-header">
        <h3><span class="badge badge-secondary">EZ WIN</span></h3>
    </div>
    <div class="card-body">
        <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@Model.Champion.ImageUrl" alt="Alternate Text" />
        <h3 class="card-text">@Model.Champion.Name</h3>
        <h5><span class="badge badge-primary">Items</span></h5>
        <div class="d-flex justify-content-center">
            @foreach (var item in Model.Build)
            {
                <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@item.ImageUrl" width="55" data-toggle="tooltip" title="@item.Name" />
            }
        </div>
    </div>
    <div>
        <img src="@Model.Position.ImageUrl" alt="Alternate Text" width="50" />
    </div>
    <div>
        <h5><span class="badge badge-success">Summoner Spells</span></h5>
        @foreach (var summonerSpell in Model.SummonerSpells)
        {
            <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@summonerSpell.ImageUrl" width="50" data-toggle="tooltip" title="@summonerSpell.Name" />
        }

    </div>
    <div class="card-footer text-muted">
        Tip: Do not change any items otherwise the build will not work as planned XD!
    </div>
</div>

src/LeagueDraft.Web/Views/Draft/MakeDraftByPosition.cshtml
@model DraftByPositionViewModel
@{
    ViewData["Title"] = Model.Position.Name + " " + "Draft";
}
<div class="text-center">
    <img src="@Model.Position.ImageUrl" width="75" />
    <h1 class="display-4">@Model.Position.Name Setup</h1>
</div>
<br />
<div class="card text-center">
    <div class="card-header">
        <h3><span class="badge badge-secondary">EZ WIN</span></h3>
    </div>
    <div class="card-body">
        <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@Model.Champion.ImageUrl" alt="Alternate Text" />
        <h3 class="card-text">@Model.Champion.Name</h3>
        <h5><span class="badge badge-primary">Items</span></h5>
        <div class="d-flex justify-content-center">
            @foreach (var item in Model.Build)
            {
                <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@item.ImageUrl" width="55" data-toggle="tooltip" title="@item.Name" />
            }

        </div>
    </div>
    <div>
        <h5><span class="badge badge-success">Summoner Spells</span></h5>
        @foreach (var summonerSpell in Model.SummonerSpells)
        {
            <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@summonerSpell.ImageUrl" width="50" data-toggle="tooltip" title="@summonerSpell.Name" />
        }

    </div>
    <div class="card-footer text-muted">
        Tip: Do not change any items otherwise the build will not work as planned XD!
    </div>
</div>

src/LeagueDraft.Web/Views/Draft/MakeSoloDraft.cshtml
@model DraftViewModel
@{
    ViewData["Title"] = Model.Champion.Name + " " + "Draft";
}


<div class="text-center">
    <h1 class="display-4">Champion Setup</h1>
</div>
<br />
<div class="card text-center">
    <div class="card-header">
        <h3><span class="badge badge-secondary">EZ WIN</span></h3>
    </div>
    <div class="card-body">
        <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@Model.Champion.ImageUrl" alt="Alternate Text" />
        <h3 class="card-text">@Model.Champion.Name</h3>
        <h5><span class="badge badge-primary">Items</span></h5>
        <div class="d-flex justify-content-center">
            @foreach (var item in Model.Build)
            {
                <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@item.ImageUrl" width="55" data-toggle="tooltip" title="@item.Name" />
            }
        </div>
    </div>
    <div>
        <img src="@Model.Position.ImageUrl" alt="Alternate Text" width="50" />
    </div>
    <div>
        <h5><span class="badge badge-success">Summoner Spells</span></h5>
        @foreach (var summonerSpell in Model.SummonerSpells)
        {
            <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@summonerSpell.ImageUrl" width="50" data-toggle="tooltip" title="@summonerSpell.Name" />
        }

    </div>
    <div class="card-footer text-muted">
        Tip: Do not cheat on the build or spells!
    </div>
</div>

src/LeagueDraft.Web/Views/Draft/MakeTeamDraft.cshtml
@model TeamDraftViewModel
@{
    ViewData["Title"] = "MakeTeamDraft";
}
<div class="text-center">
    <h1 class="display-4">Team Setup</h1>
</div>
<br />

<div class="card text-center">
    <div class="card-header">
        <h3><span class="badge badge-secondary">EZ WIN</span></h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <h5 class="display-4">Champions</h5>
                @foreach (var champion in Model.TeamSet)
                {
                    <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@champion.Champion.ImageUrl" width="50" data-toggle="tooltip" title="@champion.Champion.Name" />
                    <br />
                }
            </div>
            <div class="col">
                <h5 class="display-4">Spells</h5>
                @foreach (var item in Model.TeamSet)
                {
                    @foreach (var spell in item.SummonerSpells)
                    {

                        <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@spell.ImageUrl" width="50" data-toggle="tooltip" title="@spell.Name" />
                    }
                    <br />
                }
            </div>
            <div class="col">
                <h5 class="display-4">Builds</h5>
                @foreach (var build in Model.TeamSet)
                {
                    foreach (var item in build.Build)
                    {
                        <img class="border" style="border-width:5px !important; border-radius: 10px;" src="@item.ImageUrl" width="50" data-toggle="tooltip" title="@item.Name" />
                    }
                    <br />
                }
            </div>
        </div>
    </div>
</div>
<div class="card-footer text-muted text-center">
    Tip: Do not change any items otherwise the build will not work as planned XD!
</div>